/* Original teaching content. Russian source vocabulary is kept for progress compatibility. */
(function(root){
const ru=root.CURRICULUM;
const courses={ru:{name:'Russe',native:'Русский',code:'ru-RU',mark:'Я',intro:'Des premiers mots aux conversations à deux.',chapters:ru.chapters.map(x=>x[0]),alphabet:ru.alphabet,lessons:ru.lessons.map(l=>({...l,lang:'ru',words:l.words.map(w=>({...w,text:w.ru,latin:null}))}))},zh:{name:'Chinois',native:'中文',code:'zh-CN',mark:'文',intro:'Le mandarin, pas à pas, depuis le français.',chapters:['Les premiers échanges','Construire une phrase','Le quotidien'],lessons:[]}};
// Keep the second reading lesson within letters introduced so far.
const r2=courses.ru.lessons[1];r2.words=[['сок','jus'],['нос','nez'],['рот','bouche'],['сон','sommeil'],['хор','chœur'],['у́тро','matin']].map(([text,fr],i)=>({id:'r6l02w'+i,text,ru:text,fr,lesson:'l02'}));
r2.rule='В se lit v, Н se lit n, Р se lit r, С se lit s, У se lit ou et Х se lit kh.\nLis НОС : n + o + s. Cela donne « nos », le nez. Lis ensuite СОК : s + o + k, le jus.\nLe russe roule le r avec la langue. Le son kh se produit au fond de la bouche ; il ne ressemble pas au h muet français.';
function add(lang,id,ch,title,goal,rule,rows,clozes=[]){const c=courses[lang];c.lessons.push({id,lang,ch,title,goal,rule,words:rows.map(([text,latin,fr],i)=>({id:id+'w'+i,lesson:id,text,latin,fr})),clozes:clozes.map(([prompt,answer,choices,explain])=>({prompt,answer,choices,explain}))});}
courses.ru.chapters.push('À deux · avec ta copine');
add('ru','ru-couple1',6,'Les petits mots du quotidien','Dire bonjour, remercier et souhaiter une bonne nuit.','Привет est familier : parfait avec ta copine. Доброе утро se dit le matin.\nСпокойной ночи se dit quand on va dormir. Ce n’est pas une salutation en arrivant le soir.',[['Приве́т',null,'Salut'],['До́брое у́тро',null,'Bonjour (le matin)'],['Спаси́бо',null,'Merci'],['Споко́йной но́чи',null,'Bonne nuit']], [['Que dis-tu juste avant de dormir ?','Спокойной ночи',['Спокойной ночи','Доброе утро','Спасибо'],'Спокойной ночи souhaite une nuit paisible.']]);
add('ru','ru-couple2',6,'Prendre de ses nouvelles','Demander comment elle va et répondre simplement.','Как прошёл твой день? signifie « Comment s’est passée ta journée ? ». День est masculin, donc прошёл.\nХорошо peut être une réponse courte : « bien ». Et А у тебя? renvoie la question : « Et toi ? ».',[['Как дела́?',null,'Comment ça va ?'],['Хорошо́',null,'Bien'],['А у тебя́?',null,'Et toi ?'],['Как прошёл твой день?',null,'Comment s’est passée ta journée ?']]);
add('ru','ru-couple3',6,'Dire ce que tu ressens','Exprimer de l’affection avec des phrases naturelles.','Я тебя люблю signifie « Je t’aime ». Тебя correspond à « te » dans cette phrase.\nЯ скучаю по тебе signifie « Tu me manques ». La construction russe est différente : on ne traduit pas chaque mot du français.\nРад est employé par un homme ; une femme dit рада.',[['Я тебя́ люблю́',null,'Je t’aime'],['Я скуча́ю по тебе́',null,'Tu me manques'],['Ты краси́вая',null,'Tu es belle'],['Я рад тебя́ ви́деть',null,'Je suis content de te voir (homme)']]);
add('ru','ru-couple4',6,'Proposer un moment ensemble','Inviter à se promener et fixer un rendez-vous.','Давай + verbe propose une activité à deux. Давай погуляем : « Allons nous promener ».\nВо сколько? demande l’heure d’un événement. В семь : à sept heures.\nEssaie ensuite une vraie invitation ; l’application vérifie ici les modèles appris.',[['Дава́й погуля́ем',null,'Allons nous promener'],['Ты хо́чешь чаю́?',null,'Veux-tu du thé ?'],['Во ско́лько?',null,'À quelle heure ?'],['До встре́чи',null,'À bientôt']]);
add('zh','zh01',0,'Bonjour, les tons !','Reconnaître les tons et saluer.','Le mandarin utilise des tons : la mélodie fait partie du mot. 1 : haut et stable (mā) ; 2 : montant (má) ; 3 : bas, puis remontant isolément (mǎ) ; 4 : descendant (mà). Sans accent : ton neutre, bref.\nLe pinyin écrit les sons en lettres latines. Les accents indiquent les tons : ne les supprime pas dans les exercices de pinyin.\n你好 s’écrit nǐ hǎo. À l’oral, le premier troisième ton devient montant devant le second : ní hǎo. Le pinyin de référence garde nǐ hǎo.',[['你好','nǐ hǎo','Bonjour'],['你','nǐ','tu / vous (singulier)'],['好','hǎo','bien / bon'],['再见','zài jiàn','Au revoir']], [['Quel signe correspond au quatrième ton, descendant ?','à',['ā','á','ǎ','à'],'Le quatrième ton descend nettement : à.']]);
add('zh','zh02',0,'Merci et s’il te plaît','Être poli dans les échanges simples.','谢谢 : la deuxième syllabe est neutre. 不客气 répond à un remerciement.\n不 est normalement bù ; devant un quatrième ton il se prononce bú, comme dans 不客气 (bú kèqi).\n请 précède une demande. 对不起 s’utilise pour présenter des excuses.',[['谢谢','xiè xie','Merci'],['不客气','bú kè qi','De rien'],['请','qǐng','S’il te plaît / s’il vous plaît'],['对不起','duì bu qǐ','Pardon']]);
add('zh','zh03',0,'Je m’appelle…','Te présenter et demander un prénom.','我 = je, 你 = tu. 叫 signifie « s’appeler » dans 我叫… : ajoute ton prénom à la suite.\nLe verbe ne change pas avec la personne. 我叫 et 你叫 gardent le même 叫.\nPour demander le prénom : 你叫什么名字？ littéralement « tu t’appelles quel nom ? ».',[['我','wǒ','je / moi'],['叫','jiào','s’appeler'],['名字','míng zi','prénom / nom'],['你叫什么名字','nǐ jiào shén me míng zi','Comment t’appelles-tu ?']], [['Comment commence « Je m’appelle… » ?','我叫',['我叫','你叫','名字'],'我 (je) + 叫 (s’appeler), puis ton prénom.']]);
add('zh','zh04',0,'Compter jusqu’à cinq','Lire et prononcer les cinq premiers nombres.','Les caractères ne sont pas un alphabet : chacun associe une forme, une prononciation et un sens. Observe 一, 二, 三 : un, deux, trois traits.\nPour écrire à la main, il faut aussi apprendre l’ordre des traits. Ici, tu apprends à reconnaître les caractères et à saisir le pinyin.',[['一','yī','un'],['二','èr','deux'],['三','sān','trois'],['四','sì','quatre'],['五','wǔ','cinq']]);
add('zh','zh05',1,'Être et ne pas être','Dire que tu es français.','是 relie une personne à une identité : 我是法国人, « Je suis français ».\nPour nier, ajoute 不 avant 是 : 我不是… 不 se prononce bú devant le quatrième ton de shì.\n人 signifie « personne » : 法国 (France) + 人 = Français.',[['是','shì','être (identité)'],['不是','bú shì','ne pas être'],['法国人','fǎ guó rén','Français / Française'],['我是法国人','wǒ shì fǎ guó rén','Je suis français / française']], [['Complète : 我___法国人。 (Je suis français.)','是',['是','你','吗'],'是 relie 我 et 法国人.']]);
add('zh','zh06',1,'Poser une question','Transformer une affirmation en question.','Ajoute 吗 à la fin d’une affirmation pour poser une question oui/non : 你是法国人吗？\n吗 se prononce ma, sans ton marqué. Ne l’ajoute pas à une question qui contient déjà 什么 (quoi).\n呢 permet de renvoyer une question : 你呢？ = Et toi ?',[['吗','ma','particule de question oui/non'],['你呢','nǐ ne','Et toi ?'],['你是法国人吗','nǐ shì fǎ guó rén ma','Es-tu français / française ?'],['什么','shén me','quoi / quel']], [['Où place-t-on 吗 ?','À la fin',['À la fin','Au début','Avant chaque verbe'],'吗 se place à la fin de la phrase affirmative.']]);
add('zh','zh07',1,'Aimer et vouloir','Parler de tes envies.','喜欢 signifie « aimer / apprécier ». 想 devant un verbe exprime l’envie : 我想喝茶, « Je voudrais boire du thé ».\nOrdre de base : sujet + verbe + complément. 我 + 喜欢 + 茶.\nPour nier : 不喜欢, « ne pas aimer ».',[['喜欢','xǐ huan','aimer / apprécier'],['想','xiǎng','vouloir / avoir envie'],['我喜欢茶','wǒ xǐ huan chá','J’aime le thé'],['我想喝茶','wǒ xiǎng hē chá','Je voudrais boire du thé']]);
add('zh','zh08',1,'Six à dix','Compléter les nombres de base.','Après dix, on combine : 十一 = dix-un = onze, 十二 = douze. 二十 = deux-dix = vingt.\n六 liù : iu représente une suite de sons proche de iou. 七 qī : q est un son aspiré, proche de « tchi » mais différent du français.',[['六','liù','six'],['七','qī','sept'],['八','bā','huit'],['九','jiǔ','neuf'],['十','shí','dix']], [['Comment écrit-on onze ?','十一',['十一','二十','一十'],'十一 signifie dix + un.']]);
add('zh','zh09',2,'À boire et à manger','Reconnaître les mots utiles à table.','喝 signifie boire, 吃 signifie manger. On dit 喝水 (boire de l’eau) et 吃米饭 (manger du riz cuit).\nPas d’article obligatoire comme « du » : 喝 + 水 suffit. 茶 est le thé, sans préciser une variété.',[['水','shuǐ','eau'],['茶','chá','thé'],['喝','hē','boire'],['吃','chī','manger'],['米饭','mǐ fàn','riz cuit']]);
add('zh','zh10',2,'Aujourd’hui et demain','Situer une action dans le temps.','Le verbe ne se conjugue pas au futur. Le contexte et des mots comme 明天 indiquent le temps.\nPlace le temps avant le verbe : 我明天去北京 (Moi, demain, aller à Pékin).\n今天 = aujourd’hui ; 明天 = demain ; 昨天 = hier.',[['今天','jīn tiān','aujourd’hui'],['明天','míng tiān','demain'],['昨天','zuó tiān','hier'],['现在','xiàn zài','maintenant']]);
add('zh','zh11',2,'Où est… ?','Demander un lieu et comprendre une réponse.','在 situe une personne ou une chose : 我在这里, « Je suis ici ».\n哪里 signifie où. Dans 厕所在哪里？, le mot interrogatif reste à la place de la réponse.\nNe rajoute pas 吗 : 哪里 suffit à faire la question.',[['哪里','nǎ lǐ','où'],['这里','zhè lǐ','ici'],['那里','nà lǐ','là-bas'],['厕所在哪里','cè suǒ zài nǎ lǐ','Où sont les toilettes ?']]);
add('zh','zh12',2,'Se faire comprendre','Demander de répéter ou de parler lentement.','听 signifie écouter / entendre et 懂 comprendre. 听不懂 : ne pas comprendre ce qu’on entend.\n请慢一点 signifie « Un peu plus lentement, s’il vous plaît ». 一 se prononce ici yì devant le troisième ton de 点.\nUtilise ces phrases dans un vrai échange : savoir demander de l’aide fait partie de l’apprentissage.',[['我听不懂','wǒ tīng bu dǒng','Je ne comprends pas (à l’oral)'],['请再说一遍','qǐng zài shuō yí biàn','Répétez encore une fois, s’il vous plaît'],['请慢一点','qǐng màn yì diǎn','Plus lentement, s’il vous plaît'],['没关系','méi guān xi','Ce n’est pas grave']]);
root.COURSES=courses;
})(typeof window!=='undefined'?window:globalThis);
