(function(root){
const day=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const plain=s=>String(s).normalize('NFD').replace(/\u0301/g,'').normalize('NFC');
const norm=(s,lang='ru')=>(lang==='ru'?plain(s).replace(/ё/gi,'е'):String(s).normalize('NFC')).toLowerCase().replace(/[.,!?;:。！？，、«»“”"—–]/g,'').replace(/\s+/g,lang==='zh'?'':' ').trim();
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const merge=(a,b)=>[...new Map([...a,...b].map(e=>[e.id,e])).values()].sort((a,b)=>a.at.localeCompare(b.at)||a.id.localeCompare(b.id));
function parse(raw){const p=typeof raw==='string'?JSON.parse(raw):raw;if(!p||![1,2].includes(p.schema)||!Array.isArray(p.events)||p.events.length>100000)throw Error('Fichier JSON non reconnu. Ta progression existante reste intacte.');for(const e of p.events){if(!e||typeof e.id!=='string'||!e.id||typeof e.at!=='string'||!Number.isFinite(Date.parse(e.at))||!/^\d{4}-\d{2}-\d{2}$/.test(e.day)||!['answer','complete','writing'].includes(e.kind)||e.lang&&!['ru','zh'].includes(e.lang)||e.kind==='answer'&&typeof e.correct!=='boolean'||e.kind==='complete'&&(!Number.isFinite(e.score)||e.score<0||e.score>100||typeof e.lesson!=='string'))throw Error('Le fichier contient un événement invalide. Rien n’a été remplacé.');}return p.events;}
function derive(events,lang,now=Date.now()){
const days=Object.create(null),words=Object.create(null),lessons=Object.create(null);let answers=0,correct=0;
for(const e of events.filter(e=>(e.lang||'ru')===lang)){const d=days[e.day]??={answers:0,correct:0,lessons:new Set()};if(e.kind==='answer'){answers++;d.answers++;if(e.correct){correct++;d.correct++}if(e.word){const w=words[e.word]??={streak:0,seen:0,due:0};w.seen++;w.streak=e.correct?w.streak+1:0;w.due=Date.parse(e.at)+(e.correct?[1,3,7,14,30][Math.min(4,w.streak-1)]*86400000:600000);}}if(e.kind==='complete'){const l=lessons[e.lesson]??={best:0,passed:false};l.best=Math.max(l.best,e.score);l.passed=l.best>=80;d.lessons.add(e.lesson);}}
let cursor=new Date(now),streak=0;if(!days[day(cursor)]?.answers)cursor.setDate(cursor.getDate()-1);while(days[day(cursor)]?.answers){streak++;cursor.setDate(cursor.getDate()-1)}
return{days,words,lessons,answers,correct,streak,due:Object.keys(words).filter(k=>words[k].due<=now),retained:Object.values(words).filter(w=>w.streak>=3).length};}
function questions(lesson,course,audio=false,reviewWords=null){const words=reviewWords||lesson.words,pool=course.lessons.flatMap(l=>l.words),out=[];for(const w of words){const choices=shuffle([w.fr,...shuffle([...new Set(pool.filter(x=>x.fr!==w.fr).map(x=>x.fr))]).slice(0,3)]);out.push({type:'choice',word:w,prompt:'Quel est le sens de cette expression ?',text:w.text,answer:w.fr,choices});out.push({type:course.code==='ru-RU'?'write':'pinyin',word:w,prompt:course.code==='ru-RU'?'Écris en russe':'Écris le pinyin, avec les tons',text:course.code==='ru-RU'?w.fr:w.text,answer:course.code==='ru-RU'?plain(w.text):w.latin});}
if(audio&&words.length){const w=words[Math.floor(Math.random()*words.length)];out.push({type:'audio',word:w,prompt:'Écoute et retrouve le sens',answer:w.fr,choices:shuffle([w.fr,...shuffle([...new Set(pool.filter(x=>x.fr!==w.fr).map(x=>x.fr))]).slice(0,3)])});}
if(!reviewWords){for(const c of lesson.clozes.slice(0,2))out.push({type:'rule',prompt:c.prompt,answer:c.answer,choices:shuffle(c.choices),explain:c.explain});if(lesson.reading)out.push({type:'reading',prompt:lesson.reading.question,text:lesson.reading.ru,answer:lesson.reading.answer,choices:shuffle(lesson.reading.choices),explain:lesson.reading.fr});}
// Recognition first, retrieval second: never show a word immediately before asking to write it.
return [...shuffle(out.filter(q=>q.type==='choice')),...shuffle(out.filter(q=>q.type!=='choice'))];}
root.LearnCore={day,plain,norm,shuffle,merge,parse,derive,questions};if(typeof module!=='undefined')module.exports=root.LearnCore;
})(typeof window!=='undefined'?window:globalThis);
