const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{const fakeVoice={name:'Russian test voice',lang:'ru-RU',voiceURI:'test-ru',localService:true};Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[fakeVoice],addEventListener:()=>{},cancel:()=>{},speak:u=>setTimeout(()=>u.onend?.(),5)},configurable:true});});
await page.goto('file://'+path.resolve(__dirname,'../index.html'));
assert.equal(await page.locator('h1').textContent(),'Un peu de russe.Un peu plus loin.');
await page.getByRole('button',{name:'02 Mon parcours'}).click();assert.equal(await page.locator('.lesson-card').count(),30);assert.equal(await page.locator('[data-lesson="l02"]').isDisabled(),true);
await page.locator('[data-lesson="l01"]').click();assert.equal(await page.locator('.vocab-card').count(),6);
await page.locator('#latin-toggle').uncheck();assert.equal(await page.locator('.vocab-card .latin').count(),0);
await page.getByRole('button',{name:'M’entraîner →'}).click();assert.ok(await page.locator('#validate').isVisible());
await page.locator('#validate').click();assert.equal(await page.evaluate(()=>events.length),0);
async function answerQuestion(wrong=false){const q=await page.evaluate(()=>session.queue[session.index]);if(['listen','dialogue'].includes(q.type)){await page.locator('#play-question').click();await page.waitForFunction(()=>session.heard)}
if(q.choices){await page.locator('[data-choice]').filter({hasText:wrong?q.choices.find(x=>x!==q.answer):q.answer}).first().click();}
else if(q.type==='write')await page.locator('#answer').fill(wrong?'ошибка':q.answer);
else{const indices=await page.evaluate(()=>{let used=new Set();return session.queue[session.index].answer.split(/\s+/).map(w=>{const i=session.queue[session.index].words.findIndex((x,j)=>x===w&&!used.has(j));used.add(i);return i})});for(const i of indices)await page.locator(`[data-word="${i}"]`).click();}
await page.locator('#validate').click();assert.ok(await page.locator('.feedback').isVisible());const count=await page.evaluate(()=>events.length);await page.locator('#validate').click();assert.equal(await page.evaluate(()=>events.filter(e=>e.kind==='answer').length),count);}
await answerQuestion(true);assert.equal(await page.evaluate(()=>events[0].correct),false);
while(await page.locator('.exercise-card').count())await answerQuestion();
assert.equal(await page.evaluate(()=>state().lessons.l01?.passed||false),false);await page.locator('#take-test').click();
while(await page.locator('.exercise-card').count())await answerQuestion();assert.equal(await page.evaluate(()=>state().lessons.l01.passed),true);
await page.locator('#end-session').click();await page.getByRole('button',{name:'02 Mon parcours'}).click();assert.equal(await page.locator('[data-lesson="l02"]').isDisabled(),false);
await page.getByRole('button',{name:'03 Alphabet & sons'}).click();assert.equal(await page.locator('[data-letter]').count(),33);await page.locator('[data-letter="14"]').click();assert.ok((await page.locator('#letter-detail').textContent()).includes('cette lettre se lit n'));
await page.locator('#letter-drill').click();while(await page.evaluate(()=>session.queue[session.index].type!=='write'))await answerQuestion();await page.locator('[data-key="я"]').click();assert.equal(await page.locator('#answer').inputValue(),'я');await page.locator('[data-key="back"]').click();assert.equal(await page.locator('#answer').inputValue(),'');await page.locator('[data-key="ю"]').click();await page.locator('[data-key="clear"]').click();assert.equal(await page.locator('#answer').inputValue(),'');
await page.getByRole('button',{name:'05 Mon journal'}).click();assert.ok(await page.locator('.day.active').count());await page.locator('.day.active').first().click();assert.ok((await page.locator('#day-detail').textContent()).includes('Réponses'));
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'01 Aujourd’hui'}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:path.resolve(__dirname,'../../mobile.png'),fullPage:true});
await page.setViewportSize({width:1440,height:1050});await page.screenshot({path:path.resolve(__dirname,'../../desktop.png'),fullPage:true});
let remote={schema:1,events:[{id:'other-device',at:'2026-10-01T12:00:00Z',day:'2026-10-01',kind:'answer',skill:'lecture',correct:true}]},posts=0;
await page.route('https://poekhali-progress.osharkio.chatgpt.site/api/progress',async route=>{if(route.request().method()==='POST'){posts++;const body=JSON.parse(route.request().postData());const ids=new Set(remote.events.map(e=>e.id));for(const e of body.events)if(!ids.has(e.id)){remote.events.push(e);ids.add(e.id)}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,accepted:body.events.length})})}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(remote)})});
await page.getByRole('button',{name:'06 Sauvegarde & audio'}).click();assert.ok(await page.locator('#activate-cloud').isVisible());await page.evaluate(()=>rememberSession('test.session.only'));await page.evaluate(()=>sync());assert.ok(posts);assert.ok(await page.evaluate(()=>events.some(e=>e.id==='other-device')));assert.equal(await page.evaluate(()=>pending.length),0);const before=remote.events.length;await page.evaluate(()=>addEvent({kind:'answer',skill:'lecture',correct:true}));await page.evaluate(()=>sync());assert.equal(remote.events.length,before+1);assert.equal(await page.evaluate(()=>localStorage.length),1);
assert.deepEqual(errors,[]);await browser.close();console.log('Browser OK: lesson flow, test unlock, keyboard, calendar, mobile layout, audio, cloud append merging and connection-only browser storage.');})().catch(e=>{console.error(e);process.exit(1)});
