const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');
(async()=>{const root=path.resolve(__dirname,'..'),html=fs.readFileSync(root+'/index.html','utf8').replace(/<script[^>]*src[^>]*><\/script>/g,'');const dom=new JSDOM(html,{url:'https://julienh77.github.io/learn_russian/',runScripts:'dangerously'}),w=dom.window;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.confirm=()=>true;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.SpeechSynthesisUtterance=function(t){this.text=t};w.speechSynthesis={getVoices:()=>[{name:'Russian',lang:'ru-RU',voiceURI:'ru'},{name:'Chinese',lang:'zh-CN',voiceURI:'zh'}],cancel:()=>{},addEventListener:()=>{},speak:u=>u.onend?.()};let remote={schema:2,events:[]},sha='0',puts=0,conflict=false,onPut=null;const errors=[];w.addEventListener('error',e=>errors.push(e.message));
w.fetch=async(url,o)=>{assert.equal(new URL(url).origin,'https://api.github.com');if(url.includes('/branches/'))return{ok:true,json:async()=>({name:'main'})};if(o.method==='PUT'){assert.equal(o.headers.Authorization,'Bearer test-token');puts++;if(conflict){conflict=false;remote.events.push({id:'other',at:'2026-10-08T12:00:00Z',day:'2026-10-08',kind:'answer',lang:'zh',word:'zh01w0',correct:true});sha='concurrent';return{ok:false,status:409};}const body=JSON.parse(o.body);assert.equal(body.sha,sha);remote=JSON.parse(Buffer.from(body.content,'base64').toString());sha='sha'+puts;if(onPut){const f=onPut;onPut=null;f();}return{ok:true,json:async()=>({content:{sha}})};}return{ok:true,json:async()=>({type:'file',encoding:'base64',content:Buffer.from(JSON.stringify(remote)).toString('base64'),sha})};};
for(const f of ['curriculum.js','core.js','courses.js','learn-core.js','app.js'])w.eval(fs.readFileSync(root+'/'+f,'utf8')+(f==='app.js'?'\nwindow.testConnect=connect;window.testSync=sync;window.testGetQuestion=()=>session.queue[session.index];window.testEvents=()=>events;window.testState=state;window.testPending=()=>pending;window.testAdd=()=>addEvent({kind:"answer",correct:true,word:"zh01w0",skill:"write"});':'')+'\n//# sourceURL='+f);
// Evaluate lexical state inside the same global script scope via DOM-inserted helpers.
// jsdom eval calls do not share top-level lexical bindings: functions expose the state for the test.
const ev=s=>w.eval(s),$=s=>w.document.querySelector(s),all=s=>[...w.document.querySelectorAll(s)],click=s=>{assert.ok($(s),s);$(s).click();};
await new Promise(r=>setTimeout(r,0));assert.ok($('h1').textContent.includes('Un petit pas'));click('[data-action="continue"]');assert.ok($('.rule'));for(let i=0;i<7;i++)click('[data-action="next-card"]');assert.ok($('.exercise-card'));
// Runtime helper functions are added below by app's source closure in this test environment.
let q=ev('testGetQuestion()');function answer(wrong=false,hint=false){q=ev('testGetQuestion()');if(q.type==='audio')click('#hear');if(hint)click('#hint');if(q.choices)click(`[data-choice="${q.choices.indexOf(wrong?q.choices.find(x=>x!==q.answer):q.answer)}"]`);else $('#answer').value=wrong?'erreur':q.answer;click('#validate');const n=ev('testEvents().length');assert.ok($('#feedback').textContent);return n;}
answer(true);click('#validate');while($('.exercise-card')){answer();click('#validate');}assert.ok($('.result').textContent.includes('Leçon validée'));assert.equal(ev('testState().lessons.l01.passed'),true);click('[data-action="finish"]');click('[data-nav="path"]');assert.ok(!$('[data-lesson="l02"]').disabled);
// Cyrillic insertion and hint scoring.
click('[data-lesson="l02"]');for(let i=0;i<7;i++)click('[data-action="next-card"]');while(ev('testGetQuestion().type')!=='write'){answer();click('#validate');}click('[data-key="я"]');assert.equal($('#answer').value,'я');click('[data-key="back"]');assert.equal($('#answer').value,'');answer(false,true);assert.equal(ev('testEvents().at(-1).correct'),false);
// Language switch has separate progress and real pinyin tone validation.
$('#language').value='zh';$('#language').dispatchEvent(new w.Event('change'));assert.equal(ev('testState().answers'),0);click('[data-action="continue"]');for(let i=0;i<5;i++)click('[data-action="next-card"]');while(ev('testGetQuestion().type')!=='pinyin'){answer();click('#validate');}q=ev('testGetQuestion()');$('#answer').value=q.answer.normalize('NFD').replace(/[\u0300-\u036f]/g,'');click('#validate');assert.equal(ev('testEvents().at(-1).correct'),false);click('#validate');while($('.exercise-card')){answer();click('#validate');}
click('[data-action="finish"]');click('[data-nav="journal"]');assert.ok($('.day.done'));click('.day.done');assert.ok($('.journal-detail').textContent.includes('réponses'));
// GitHub conflict and new answers arriving during PUT must survive acknowledgement.
click('#save-open');$('#github-token').value='test-token';conflict=true;await ev('testConnect()');assert.ok(puts>=2);assert.ok(remote.events.some(e=>e.id==='other'));assert.equal(ev('testPending().length'),0);assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.getItem('pas-a-pas-github'),'test-token');ev('testAdd()');onPut=()=>ev('testAdd()');await ev('testSync()');assert.equal(ev('testPending().length'),1);await ev('testSync()');assert.equal(ev('testPending().length'),0);assert.equal(remote.events.length,ev('testEvents().length'));assert.ok(remote.events.some(e=>e.lang==='ru'));assert.ok(remote.events.some(e=>e.lang==='zh'));
// A fresh device with no browser storage loads both languages from the same public JSON.
const second=new JSDOM(html,{url:'https://julienh77.github.io/learn_russian/',runScripts:'dangerously'}),v=second.window;v.scrollTo=()=>{};v.TextEncoder=TextEncoder;v.TextDecoder=TextDecoder;v.fetch=async(url,o)=>{assert.equal(o.headers.Authorization,undefined);return{ok:true,json:async()=>({type:'file',encoding:'base64',content:Buffer.from(JSON.stringify(remote)).toString('base64'),sha})}};for(const f of ['curriculum.js','core.js','courses.js','learn-core.js','app.js'])v.eval(fs.readFileSync(root+'/'+f,'utf8')+(f==='app.js'?'\nwindow.loadedEvents=()=>events;':''));await new Promise(r=>setTimeout(r,0));assert.equal(v.loadedEvents().length,remote.events.length);assert.equal(v.localStorage.length,0);assert.equal(v.sessionStorage.length,0);second.window.close();
// Corrupt remote JSON must never be overwritten, and a denial retains pending answers.
ev('testAdd()');const before=puts;remote={schema:200,events:[]};await ev('testSync()');assert.equal(puts,before);assert.equal(ev('testPending().length'),1);assert.ok($('#save-status').textContent.includes('vérifier'));assert.deepEqual(errors,[]);dom.window.close();console.log('DOM OK: complete Russian and Chinese lessons, errors, hints, keyboard, tones, calendar, GitHub conflicts, in-flight events, corrupt JSON and credential-only storage.');})().catch(e=>{console.error(e);process.exit(1)});
