const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {JSDOM}=require('jsdom');
(async()=>{const root=path.resolve(__dirname,'..');const html=fs.readFileSync(root+'/index.html','utf8').replace(/<script[^>]*src[^>]*><\/script>/g,'');const dom=new JSDOM(html,{url:'https://julienh77.github.io/learn_russian/',runScripts:'dangerously'});const w=dom.window;const errors=[];w.addEventListener('error',e=>errors.push(e.message));w.scrollTo=()=>{};w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.confirm=()=>true;w.SpeechSynthesisUtterance=function(text){this.text=text};w.speechSynthesis={getVoices:()=>[{name:'Test Russian',lang:'ru-RU',voiceURI:'test-ru'}],addEventListener:()=>{},cancel:()=>{},speak:u=>u.onend?.()};
for(const f of ['curriculum.js','core.js','app.js']){const script=w.document.createElement('script');script.textContent=fs.readFileSync(root+'/'+f,'utf8');w.document.body.append(script)}
const $=s=>w.document.querySelector(s),all=s=>[...w.document.querySelectorAll(s)],ev=s=>w.eval(s);const click=s=>{assert.ok($(s),s);$(s).click()};
assert.ok($('h1').textContent.includes('Un peu de russe'));click('[data-page="course"]');assert.equal(all('.lesson-card').length,30);assert.ok($('[data-lesson="l02"]').disabled);click('[data-lesson="l01"]');assert.equal(all('.vocab-card').length,6);$('#latin-toggle').checked=false;$('#latin-toggle').dispatchEvent(new w.Event('change'));assert.equal(all('.vocab-card .latin').length,0);click('#practice');click('#validate');assert.equal(ev('events.length'),0);
function answer(wrong=false){const q=ev('session.queue[session.index]');if(['listen','dialogue'].includes(q.type))click('#play-question');if(q.choices){const i=q.choices.indexOf(wrong?q.choices.find(x=>x!==q.answer):q.answer);click(`[data-choice="${i}"]`)}else if(q.type==='write')$('#answer').value=wrong?'ошибка':q.answer;else{const used=new Set();for(const word of q.answer.split(/\s+/)){const i=q.words.findIndex((x,j)=>x===word&&!used.has(j));used.add(i);click(`[data-word="${i}"]`)}}
click('#validate');assert.ok($('.feedback'));const n=ev('events.filter(e=>e.kind==="answer").length');click('#validate');assert.equal(ev('events.filter(e=>e.kind==="answer").length'),n);}
answer(true);assert.equal(ev('events[0].correct'),false);while($('.exercise-card'))answer();assert.equal(ev('state().lessons.l01?.passed||false'),false);click('#take-test');while($('.exercise-card'))answer();assert.equal(ev('state().lessons.l01.passed'),true);click('#end-session');click('[data-page="course"]');assert.ok(!$('[data-lesson="l02"]').disabled);
click('[data-page="alphabet"]');assert.equal(all('[data-letter]').length,33);click('[data-letter="14"]');assert.ok($('#letter-detail').textContent.includes('cette lettre se lit n'));click('#letter-drill');while(ev('session.queue[session.index].type')!=='write')answer();click('[data-key="я"]');assert.equal($('#answer').value,'я');click('[data-key="back"]');assert.equal($('#answer').value,'');click('[data-key="ю"]');click('[data-key="clear"]');assert.equal($('#answer').value,'');
click('[data-page="journal"]');assert.ok(all('.day.active').length);click('.day.active');assert.ok($('#day-detail').textContent.includes('Réponses'));const monthBefore=$('.calendar').textContent;click('#prev-month');assert.notEqual($('.calendar').textContent,monthBefore);
let remote={schema:1,events:[]},sha='old',puts=0,conflict=true;
w.fetch=async(url,options)=>{if(options.method==='PUT'){puts++;const body=JSON.parse(options.body);if(conflict){conflict=false;remote.events.push({id:'other-device',at:'2026-10-01T12:00:00Z',day:'2026-10-01',kind:'answer',skill:'lecture',correct:true});sha='changed';return{ok:false,status:409}}assert.equal(body.sha,sha);remote=JSON.parse(Buffer.from(body.content,'base64').toString());sha='new';assert.ok(!JSON.stringify(remote).includes('test-token'));return{ok:true,json:async()=>({})}}
if(url.includes('/contents/'))return{ok:true,json:async()=>({type:'file',encoding:'base64',sha,content:Buffer.from(JSON.stringify(remote)).toString('base64')})};return{ok:true,json:async()=>({private:true,permissions:{push:true}})}};
click('[data-page="settings"]');$('[name="token"]').value='test-token-not-real';const form=$('#github-form');await form.onsubmit({preventDefault(){},target:form});assert.ok(puts>=2);assert.ok(remote.events.some(e=>e.id==='other-device'));assert.equal(ev('pending.length'),0);assert.equal($('[name="token"]').value,'');const count=remote.events.length;ev('addEvent({kind:"answer",skill:"lecture",correct:true})');await ev('sync()');assert.equal(remote.events.length,count+1);assert.equal(ev('pending.length'),0);
w.fetch=async()=>({ok:false,status:403});ev('addEvent({kind:"answer",skill:"lecture",correct:false})');await ev('sync()');assert.equal(ev('pending.length'),1);assert.ok($('#save-status').textContent.includes('Échec'));assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.length,0);assert.deepEqual(errors,[]);dom.window.close();console.log('DOM OK: all lesson flow, exam unlock, keyboard, audio completion, calendar, GitHub conflict merging/failure and no browser storage.');})().catch(e=>{console.error(e);process.exit(1)});
